In [81]:
import pandas as pd
import random

In [82]:
numeros = random.sample(range(1,52), 3)

In [83]:
serie = pd.Series(numeros)

In [84]:
serie

0     2
1    29
2    38
dtype: int64

# Média

In [85]:
media = serie.mean()

In [86]:
print(media)

23.0

## Variância

In [87]:
print(serie.var())

351.0

In [88]:
serie.describe()

count     3.000000
mean     23.000000
std      18.734994
min       2.000000
25%      15.500000
50%      29.000000
75%      33.500000
max      38.000000
dtype: float64

In [89]:
# serie = serie.sort_values

In [90]:
serie

0     2
1    29
2    38
dtype: int64

## Usando o índice como referência

In [91]:
print(serie[0])

2

## Ignorando as chaves e utilizando a posição como referência e pode ser usado com fateamento

In [92]:
print(serie.iloc[0])

2

## Mudando os índices e vinculando ao valor

In [93]:
indices = [
    "Sandro", "Paula", "Priscila"
]

In [94]:
serie = pd.Series(numeros, index=indices)

In [95]:
serie

Sandro       2
Paula       29
Priscila    38
dtype: int64

In [97]:
print(serie["Sandro"])

2

o **iloc** navega pelas linhas (número da linha) que não é a mesma coisa índices

In [100]:
print(serie.iloc["Sandro"])

TypeError: Cannot index by location index with a non-integer key

Outra possibilidade de usar o índice, também pode ser utilizado o loc. Na prática terá o mesmo efeito da busca como uma lista.

In [102]:
print(serie.loc["Paula"])

29

## Criando um dataframe

In [103]:
df = pd.DataFrame()

In [ ]:
df["Nomes"] = indices

In [112]:
df["Valores"] = numeros

In [113]:
df

      Nomes  Valores
0    Sandro        2
1     Paula       29
2  Priscila       38

In [114]:
df["Nomes"]

0      Sandro
1       Paula
2    Priscila
Name: Nomes, dtype: str

Fazendo a analogia - um dataframe é um planilha - cada coluna é uma Serie. Mas também, pode obter uma série em nível de linha.

In [115]:
df.iloc[2]

Nomes      Priscila
Valores          38
Name: 2, dtype: object

In [116]:
type(df.iloc[2])

pandas.Series

In [117]:
df

      Nomes  Valores
0    Sandro        2
1     Paula       29
2  Priscila       38

In [118]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [119]:
df.iloc[0]["Nomes"]

'Sandro'

In [121]:
print(df.iloc[-1]["Valores"])

38