In [1]:
import pandas as pd

In [2]:
transacoes = pd.read_csv("data/transacoes.csv", sep=';')

In [3]:
produtos = pd.read_csv("data/produtos.csv", sep=';')

In [4]:
clientes = pd.read_csv("data/clientes.csv", sep=';')

In [5]:
clientes.head()

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao
0,000dc0f6-e4f2-4a42-b8cd-b586ed1c709a,0,1,0,0,0,2,2025-11-13 12:03:56.114,2025-12-13 11:45:37.364
1,000ff655-fa9f-4baa-a108-47f581ec52a1,0,0,0,0,0,25086,2024-02-01 00:00:00.000,2025-09-26 13:28:37.697
2,001749bd-37b5-4b1e-8111-f9fbba90f530,0,0,0,0,0,50,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
3,0019bb9e-26d4-4ebf-8727-fc911ea28a92,0,0,0,0,0,2,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
4,0028dda2-334f-40bb-9582-475fb6719471,1,1,1,0,0,1100,2025-10-29 02:08:18.367,2026-02-24 04:49:02.551

In [6]:
clientes.to_json("clientes.json", index=False)

### Copiando os dados do Control + C -> Control + V (arquivo bobo.csv)

In [7]:
df = pd.read_clipboard(sep=',')

In [8]:
df

Empty DataFrame
Columns: [https://www.twitch.tv/teomewhy]
Index: []

### Usando arquivos de páginas HTML

In [9]:
url = "https://pt.wikipedia.org/wiki/Unidades_federativas_do_Brasil"
estados = pd.read_html(url)
estados

HTTPError: HTTP Error 403: Forbidden

In [ ]:
url = "https://pt.wikipedia.org/wiki/Unidades_federativas_do_Brasil"

# Definindo um cabeçalho que simula o Chrome
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

# Lendo as tabelas da página
tabelas = pd.read_html(url, storage_options=headers)

# Geralmente a tabela dos estados é a primeira ou segunda
df_estados = tabelas[1] 
print(df_estados.head())

## Primeiras linhas

In [ ]:
clientes.head(10)

## Últimas linhas

In [ ]:
clientes.tail()

## Uma amostra aleatória

In [ ]:
clientes.sample(5)

## Atributo **shape** para determinar linhas e colunas

In [ ]:
clientes.shape

## Mostrar a lista de colunas

In [ ]:
clientes.columns

## Mostrar os índices. Caso não existe, o pandas cria um índice sequencial

In [ ]:
clientes.index

## Informações gerais

In [ ]:
clientes.info()

O valor de memória alocada é uma estimativa (inferência) determinada pelos tipos de dados do Dataframe. para o valor mais preciso, usaremos uma parâmetro memory_usage='deep'

In [ ]:
clientes.info(memory_usage='deep')

## Detalhamento do tipo das colunas

In [ ]:
clientes.dtypes

In [ ]:
type(clientes.dtypes)

Esse atributo retorna uma série com o tipo preciso de cada coluna. Assim, para verificar um tipo específico de uma coluna.

In [ ]:
clientes.dtypes['flEmail']

## Renomeando colunas

In [ ]:
transacoes.shape

In [ ]:
transacoes.info(memory_usage='deep')

In [ ]:
transacoes.dtypes

Para renomear uma coluna deve ser passado um dicionário: a chave o nome antigo, e o valor com o nome novo.

In [ ]:
transacoes.rename(columns={'QtdePontos': 'qtPontos'})

Essa alteração não reflete diretamente no Dataframe. Isso ocorre porque um novo dataframe é criado em memória com a operação realizada.

In [ ]:
transacoes.head()

Mais de uma alteração

In [ ]:
transacoes.rename(columns={'QtdePontos': 'qtPontos',
                           'DescSistemaOrigem': 'sistemaOrigem'})

Se for pensar em legibilidade, se pode criar um dicionário separado e depois passá-lo para a função rename.

In [ ]:
colunas_renomeadas = {
    'QtdePontos': 'qtPontos',
    'DescSistemaOrigem': 'sistemaOrigem'
}

In [ ]:
transacoes.rename(columns=colunas_renomeadas)

## Realizando a alteração efetivamente no dataframe

Duas formas pode ser usadas:
- Atribuindo novamente ao mesmo dataframe;
- usando o parâmetro inplace=True

In [ ]:
transacoes = transacoes.rename(columns=colunas_renomeadas)

In [ ]:
transacoes.head(2)

### Usando o parâmetro **inplace=True**

In [ ]:
transacoes.rename(columns={'DtCriacao': 'DataCriacao'}, inplace=True)

In [ ]:
transacoes.head(2)

### Navegação no dataframe

In [ ]:
transacoes['IdCliente'].iloc[1:4]

Esse comando retorna um Série do dataframe

In [ ]:
type(transacoes['IdCliente'].iloc[1:4])

### Mais de coluna

In [ ]:
transacoes['IdCliente', 'QtdePontos']

Esse erro ocorre porque apenas um valor (objeto) pode ser passado na navegação. Para isso, é usado uma lista

In [ ]:
transacoes[['IdCliente', 'QtdePontos']]

Agora diferentemente de comandos anteriores, este último comando não retorna uma série, e sim, um novo dataframe. Ele somente será uma Série, e for passado apenas uma coluna do dataframe.

In [ ]:
type(transacoes[['IdCliente', 'QtdePontos']])

### Mesclando os conceitos

In [ ]:
(transacoes[['IdCliente', 'QtdePontos']].sample(10))

## Reordenar as colunas

In [ ]:
transacoes

### Apenas para exibição

In [ ]:
transacoes[["DescSistemaOrigem","QtdePontos" ,"DataCriacao", "IdCliente"]].sample(7)

In [ ]:
listas_colunas = transacoes.columns.to_list()

In [ ]:
listas_colunas.sort()

In [ ]:
transacoes = transacoes[listas_colunas]

# Aplicando Filtros

In [ ]:
transacoes['QtdePontos'] >= 50

0         False
1         False
2         False
3         False
4         False
          ...
302236    False
302237    False
302238    False
302239    False
302240    False
Name: QtdePontos, Length: 302241, dtype: bool

In [ ]:
type(transacoes['QtdePontos'] >= 50)

pandas.Series

In [ ]:
filtro = transacoes['QtdePontos'] >= 50
transacoes[filtro]

,IdTransacao,IdCliente,DtCriacao,QtdePontos,DescSistemaOrigem
12,00028d36-4575-4d02-b2a0-bdae1bc83231,9d023e72-c799-40c0-907a-96e023a97959,2024-11-11 12:36:33.625,50,twitch
21,0003acb0-624a-4e65-bf95-426450b4434d,1b08989c-039d-4c82-879b-0f56159a1ebb,2025-11-25 12:13:19.266,50,twitch
28,0005855d-2c33-4bfd-85fe-2c7ffaf73151,f5719706-915b-4bb1-b9be-c4acb3bd7837,2025-07-16 12:05:28.007,50,twitch
32,00068e23-5b1e-432a-83df-8a5d11e495a6,3f55b86f-dc21-4ac8-8e89-7c1535359eaf,2025-01-09 12:29:28.501,50,twitch
37,00079f55-6df7-45c9-ac84-e4adb788563a,aaad5474-eb6b-4da6-9755-a1d2541c42bd,2024-08-12 14:27:40.420,50,twitch
...,...,...,...,...,...
302210,fff97b21-63f3-4289-afe8-e672b1306296,a4b70d73-1938-4f27-b1e5-973526894b10,2024-04-16 12:48:10.581,50,twitch
302219,fffb4d1f-5197-470f-936e-f7289bc5c878,9aba2685-7c0a-4d1f-8e22-0c47ca0af580,2024-02-29 12:35:20.673,50,twitch
302222,fffba02b-d70c-4bfc-aa51-a4b66b442d53,ca35412d-b340-4e7d-a391-020ec6bb6517,2024-07-04 12:53:21.075,50,twitch
302226,fffd0631-ac87-4432-bf7d-b7200fda8f0c,1dd4b8bc-f909-42bf-9748-88decb919c94,2025-10-02 11:56:38.812,50,twitch
302227,fffd47aa-3e8f-4cd1-a125-342721ad4a45,fcda54f6-b9e9-41cf-b255-0594d9947d1b,2024-08-12 12:46:44.489,100,twitch

### Mesclando o conhecimentos

In [ ]:
transacoes[transacoes['QtdePontos'] <= 50].sample(4)

,IdTransacao,IdCliente,DtCriacao,QtdePontos,DescSistemaOrigem
194282,a4a35c8b-dc7b-4955-8cd5-731538d6ebaa,69cf7f16-aa27-4501-8a8b-80c012ef84ea,2025-03-12 11:15:06.043,1,twitch
67054,38e20051-7947-439e-88bf-f5b3db4024bc,194282ca-358d-451b-9c86-30d4c797c231,2025-01-28 12:47:56.465,1,twitch
120655,66825abf-f392-4080-abd1-c36b4da108f1,65662aff-44d6-4f06-b9d9-07445c6e5943,2024-09-02 13:21:47.274,1,twitch
142107,7885911b-ddb4-4ab9-9e27-8d6f28ebe2be,afad9243-3393-41ef-9773-cea02d491e65,2024-05-20 12:45:32.439,1,twitch

É possível fazer com uma lista. Isso somente é possível por que o filtro tem a mesma dimensão do dataframe.

In [ ]:
filtro = filtro.tolist()
transacoes[filtro]

,IdTransacao,IdCliente,DtCriacao,QtdePontos,DescSistemaOrigem
12,00028d36-4575-4d02-b2a0-bdae1bc83231,9d023e72-c799-40c0-907a-96e023a97959,2024-11-11 12:36:33.625,50,twitch
21,0003acb0-624a-4e65-bf95-426450b4434d,1b08989c-039d-4c82-879b-0f56159a1ebb,2025-11-25 12:13:19.266,50,twitch
28,0005855d-2c33-4bfd-85fe-2c7ffaf73151,f5719706-915b-4bb1-b9be-c4acb3bd7837,2025-07-16 12:05:28.007,50,twitch
32,00068e23-5b1e-432a-83df-8a5d11e495a6,3f55b86f-dc21-4ac8-8e89-7c1535359eaf,2025-01-09 12:29:28.501,50,twitch
37,00079f55-6df7-45c9-ac84-e4adb788563a,aaad5474-eb6b-4da6-9755-a1d2541c42bd,2024-08-12 14:27:40.420,50,twitch
...,...,...,...,...,...
302210,fff97b21-63f3-4289-afe8-e672b1306296,a4b70d73-1938-4f27-b1e5-973526894b10,2024-04-16 12:48:10.581,50,twitch
302219,fffb4d1f-5197-470f-936e-f7289bc5c878,9aba2685-7c0a-4d1f-8e22-0c47ca0af580,2024-02-29 12:35:20.673,50,twitch
302222,fffba02b-d70c-4bfc-aa51-a4b66b442d53,ca35412d-b340-4e7d-a391-020ec6bb6517,2024-07-04 12:53:21.075,50,twitch
302226,fffd0631-ac87-4432-bf7d-b7200fda8f0c,1dd4b8bc-f909-42bf-9748-88decb919c94,2025-10-02 11:56:38.812,50,twitch
302227,fffd47aa-3e8f-4cd1-a125-342721ad4a45,fcda54f6-b9e9-41cf-b255-0594d9947d1b,2024-08-12 12:46:44.489,100,twitch

Para provar que dará erro - passar uma quantidade diferente de dimensões.

In [ ]:
filtro_errado = [False, True]
transacoes[filtro_errado]

ValueError: Item wrong length 2 instead of 302241.

### Aplicando intervalos

In [ ]:
filtro_intervalo = (transacoes['QtdePontos'] >= 50) & (transacoes['QtdePontos'] < 100)
transacoes[filtro_intervalo].tail()

,IdTransacao,IdCliente,DtCriacao,QtdePontos,DescSistemaOrigem
302206,fff723cb-e360-470d-a531-65d7d0cae718,8b7fa7ca-c541-4c97-b06f-a06b2368a1ea,2025-11-28 12:57:47.633,50,twitch
302210,fff97b21-63f3-4289-afe8-e672b1306296,a4b70d73-1938-4f27-b1e5-973526894b10,2024-04-16 12:48:10.581,50,twitch
302219,fffb4d1f-5197-470f-936e-f7289bc5c878,9aba2685-7c0a-4d1f-8e22-0c47ca0af580,2024-02-29 12:35:20.673,50,twitch
302222,fffba02b-d70c-4bfc-aa51-a4b66b442d53,ca35412d-b340-4e7d-a391-020ec6bb6517,2024-07-04 12:53:21.075,50,twitch
302226,fffd0631-ac87-4432-bf7d-b7200fda8f0c,1dd4b8bc-f909-42bf-9748-88decb919c94,2025-10-02 11:56:38.812,50,twitch

In [ ]:
transacoes[(transacoes['QtdePontos'] == 1) | (transacoes['QtdePontos'] == 100 )].sample(6)

,IdTransacao,IdCliente,DtCriacao,QtdePontos,DescSistemaOrigem
292045,f742b383-444c-4306-9d1e-38789611100f,b03c2f63-c085-4746-abe4-c9b24db1e7ef,2025-06-30 12:13:16.492,1,twitch
178178,9713167c-63ad-4d16-8c34-7f4c0d43b38a,acc75571-ba57-4cb5-bb7b-c140987ae94d,2025-12-17 13:46:07.901,1,twitch
203732,ac8d8a4a-017e-4f2f-b2c6-07c086e6f53a,4fade907-6e0f-4581-a674-aad6622b1b10,2024-11-13 12:59:13.991,100,twitch
99768,54c1b1b8-1240-43df-919c-4ec9587bbc52,f32a1cda-a38a-4d7a-bb41-b9b2aa2b08cb,2025-09-29 13:35:21.900,1,twitch
16536,0ded9945-e7fc-4f92-8377-bc189418532b,16f25c0e-f879-4453-b5d4-efebabc2881b,2025-09-25 12:22:12.352,1,twitch
166204,8cfddbfd-998c-441c-a9b1-18b78480b9b2,450a3f75-9c8a-4eb2-b39c-f718ec24f40c,2024-08-13 12:05:50.726,1,twitch

Na lógica Booleana a multiplicação é AND e a soma será o OR

1 * 0

In [ ]:
transacoes[transacoes['QtdePontos'].isin([5,100,40])]

,IdTransacao,IdCliente,DtCriacao,QtdePontos,DescSistemaOrigem
154,0020738d-ac83-4400-9ac3-efb23683ca0d,000ff655-fa9f-4baa-a108-47f581ec52a1,2025-08-06 14:34:33.669,100,twitch
164,0021337d-acc7-468b-bbb4-55bc5795e4cd,c064fb47-ba0b-4076-b15c-115d243dbecf,2025-10-17 12:41:36.543,100,twitch
238,00306432-3819-46a7-8fe1-4bccc61121b7,00a6d4c8-38e5-4e92-981e-4e4ac5084546,2024-08-27 12:01:24.968,100,twitch
387,0050ccd7-e117-464d-97e7-c03e652118bc,a8af0598-1c00-496f-8401-88d62724fed7,2025-12-05 12:17:02.208,100,twitch
430,00589e5c-a705-48a0-b705-926fe554e133,4fade907-6e0f-4581-a674-aad6622b1b10,2025-03-12 11:41:09.087,100,twitch
...,...,...,...,...,...
301771,ff937aa9-9167-4bfe-a462-78dd8deab88c,1b56823a-1f42-43ef-9295-a587f2eb9e78,2024-07-05 11:52:13.467,100,twitch
301810,ff9d2745-fe0c-40b5-ab18-1aaa161ab558,4c77c153-19b9-42e2-a03c-04f43dcc6105,2024-03-08 11:56:06.798,100,twitch
302043,ffd2339c-f7f0-42db-bbcb-2c367bbbc8b7,fcda54f6-b9e9-41cf-b255-0594d9947d1b,2024-10-03 11:31:18.565,100,twitch
302101,ffe029e1-1f33-430f-a45a-678ece053e2c,7107771a-0558-4aaa-a66e-570205a7f367,2025-05-30 14:44:18.805,100,twitch
302227,fffd47aa-3e8f-4cd1-a125-342721ad4a45,fcda54f6-b9e9-41cf-b255-0594d9947d1b,2024-08-12 12:46:44.489,100,twitch

In [13]:
clientes_pontuacao_zerados = clientes[clientes['qtdePontos'] == 0]

Neste código acima, o dataframe **clientes_pontuacao_zerados** ele aponta a referência para as linhas que se aplicam para filtro. Isso é uma vantagem já que há mais a necessidade de duplicar toda o dataframe. A mesma ideia das listas.

In [25]:
a = [1,2]
b = a

print(a)
print(b)

b.append(3)

print(a)
print(b)

b = a.copy()
b.append(4)

print("Lista A: ", a)
print("Lista B ", b)

[1, 2]
[1, 2]
[1, 2, 3]
[1, 2, 3]
Lista A:  [1, 2, 3]
Lista B  [1, 2, 3, 4]

In [ ]:
clientes_pontuacao_zerados

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao,coluna_nova
5,002970bd-65c2-42bf-a17d-2bc5e95e2f0b,0,1,0,0,0,0,2025-07-16 09:36:45.831,2025-07-16 09:36:45.831,1
7,00417bdf-844f-40bf-92e1-d663373cbbd2,0,1,0,0,0,0,2025-11-10 03:14:09.875,2025-11-10 03:14:09.875,1
8,00684343-40b5-4ce7-b2e8-71a5340973bf,0,0,0,0,0,0,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000,1
10,007b8e64-a244-4404-8992-3b8098b33ccc,0,1,0,0,0,0,2025-06-10 16:13:43.144,2025-06-10 16:13:43.144,1
11,00942a67-2ffd-4afe-a10e-3caf6e950e0f,0,1,0,0,0,0,2025-10-20 22:16:31.357,2025-10-20 22:16:31.357,1
...,...,...,...,...,...,...,...,...,...,...
5055,fe7cba1d-c594-4776-9f7f-c32aebf2404f,0,1,0,0,0,0,2025-12-07 16:25:09.216,2025-12-07 16:25:09.216,1
5057,fe830a3f-5dcb-4273-ad43-465aeeb3a460,0,1,0,0,0,0,2025-10-24 17:18:33.447,2025-10-24 17:18:33.447,1
5059,fea95103-cef1-4bf4-9b72-3af3191e8705,0,1,0,0,0,0,2025-10-31 12:21:28.962,2025-10-31 12:21:28.962,1
5060,feaf434b-e428-4445-a86e-6218c40d55ae,0,1,0,0,0,0,2025-07-08 05:14:32.687,2025-07-08 05:14:32.687,1
5072,ff8d55dc-64fa-40de-992a-04a4155f5634,0,1,0,0,0,0,2025-07-12 13:50:37.959,2025-07-12 13:50:37.959,1

In [17]:
clientes_pontuacao_zerados['coluna_nova'] = 1

In [18]:
clientes_pontuacao_zerados

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao,coluna_nova
5,002970bd-65c2-42bf-a17d-2bc5e95e2f0b,0,1,0,0,0,0,2025-07-16 09:36:45.831,2025-07-16 09:36:45.831,1
7,00417bdf-844f-40bf-92e1-d663373cbbd2,0,1,0,0,0,0,2025-11-10 03:14:09.875,2025-11-10 03:14:09.875,1
8,00684343-40b5-4ce7-b2e8-71a5340973bf,0,0,0,0,0,0,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000,1
10,007b8e64-a244-4404-8992-3b8098b33ccc,0,1,0,0,0,0,2025-06-10 16:13:43.144,2025-06-10 16:13:43.144,1
11,00942a67-2ffd-4afe-a10e-3caf6e950e0f,0,1,0,0,0,0,2025-10-20 22:16:31.357,2025-10-20 22:16:31.357,1
...,...,...,...,...,...,...,...,...,...,...
5055,fe7cba1d-c594-4776-9f7f-c32aebf2404f,0,1,0,0,0,0,2025-12-07 16:25:09.216,2025-12-07 16:25:09.216,1
5057,fe830a3f-5dcb-4273-ad43-465aeeb3a460,0,1,0,0,0,0,2025-10-24 17:18:33.447,2025-10-24 17:18:33.447,1
5059,fea95103-cef1-4bf4-9b72-3af3191e8705,0,1,0,0,0,0,2025-10-31 12:21:28.962,2025-10-31 12:21:28.962,1
5060,feaf434b-e428-4445-a86e-6218c40d55ae,0,1,0,0,0,0,2025-07-08 05:14:32.687,2025-07-08 05:14:32.687,1
5072,ff8d55dc-64fa-40de-992a-04a4155f5634,0,1,0,0,0,0,2025-07-12 13:50:37.959,2025-07-12 13:50:37.959,1

In [20]:
clientes

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao
0,000dc0f6-e4f2-4a42-b8cd-b586ed1c709a,0,1,0,0,0,2,2025-11-13 12:03:56.114,2025-12-13 11:45:37.364
1,000ff655-fa9f-4baa-a108-47f581ec52a1,0,0,0,0,0,25086,2024-02-01 00:00:00.000,2025-09-26 13:28:37.697
2,001749bd-37b5-4b1e-8111-f9fbba90f530,0,0,0,0,0,50,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
3,0019bb9e-26d4-4ebf-8727-fc911ea28a92,0,0,0,0,0,2,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
4,0028dda2-334f-40bb-9582-475fb6719471,1,1,1,0,0,1100,2025-10-29 02:08:18.367,2026-02-24 04:49:02.551
...,...,...,...,...,...,...,...,...,...
5069,ff2cabd3-3316-4b3f-8494-c25f95e90524,0,1,0,0,0,57,2025-02-10 11:12:30.631,2025-02-10 12:37:47.892
5070,ff4909ad-4e52-4767-a6fc-0fbd76e37857,0,0,0,0,0,50,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
5071,ff5d2399-6b53-49f0-b41e-fdaaa0da172a,0,1,0,0,0,2021,2025-08-25 13:09:12.556,2026-01-30 14:43:50.139
5072,ff8d55dc-64fa-40de-992a-04a4155f5634,0,1,0,0,0,0,2025-07-12 13:50:37.959,2025-07-12 13:50:37.959
5073,fff7862d-4b2c-4140-a4c5-509b48ed31b4,0,1,0,0,0,1000,2025-11-12 01:01:58.698,2025-11-12 01:02:16.561